name: cellpose-voila
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - pillow
  - ipywidgets
  - jupyterlab
  - voila
  - tqdm
  - requests
  - pyyaml
  - networkx
  - pyqt
  - shapely
  - imageio
  - tifffile
  - nbconvert
  - pip:
      - cellpose==3.1.1.1
      - torch>=2.3.0
      - fastremap
      - opencv-python-headless
      - numba
      - natsort
      - roifile
      - pyqt6
      - pyqt6-qt6
      - pyqt6-sip
      - pyqtgraph
      - superqt
      - sympy
      - scipy
      - markupsafe
      - filelock
      - tqdm
      - ipympl
      - qtpy
