name: cellpose-voila
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - pillow
  - ipywidgets
  - voila
  - pip
  - pip:
      - cellpose

